#%RAML 0.8
title: Something Cool
version: 2015-09-12
baseUri: https://somewhere.com/api
/resource:
  description: Some cool description that is really awesome
  get:
    description: Get the resource again and again
